CREATE DATABASE BdNetuno;
USE BdNetuno;

CREATE TABLE FUNCIONARIO(
COD_FUNCIONARIO INT PRIMARY KEY,
NOME_FUNCIONARIO VARCHAR (50) NOT NULL,
CPF_FUNCIONARIO VARCHAR (11) UNIQUE NOT NULL,
SENHA_FUNCIONARIO VARCHAR (50) NOT NULL,
EMAIL_FUNCIONARIO VARCHAR (120) UNIQUE NOT NULL,
TELEFONE_FUNCIONARIO VARCHAR (11) UNIQUE NOT NULL
)
 
CREATE TABLE ENDERECO(
COD_ENDERECO INT PRIMARY KEY,
CEP_ENDERECO VARCHAR (8) NOT NULL,
NUMERO_ENDERECO INT NOT NULL,
CIDADE_ENDERECO VARCHAR(30) NOT NULL,
BAIRRO_ENDERECO VARCHAR(30) NOT NULL,
RUA_ENDERECO VARCHAR(40) NOT NULL,
COMPLEMENTO_ENDERECO VARCHAR(30));

CREATE TABLE CLIENTE(
COD_CLIENTE INT PRIMARY KEY,
CPF_CLIENTE VARCHAR(11) UNIQUE NOT NULL,
NOME_CLIENTE VARCHAR(25) NOT NULL,
EMAIL_CLIENTE VARCHAR(40) UNIQUE NOT NULL,
TELEFONE_CLIENTE VARCHAR(11) NOT NULL);
 
CREATE TABLE HIDROMETRO(
COD_HIDROMETRO INT PRIMARY KEY, 
NUM_CHIP VARCHAR(10) UNIQUE NOT NULL,
NUMFAB_HIDROMETRO VARCHAR(6) UNIQUE NOT NULL,
MODELO VARCHAR(8) NOT NULL
);

CREATE TABLE LEITURA(
COD_LEITURA INT PRIMARY KEY, 
COD_HIDROMETRO INT NOT NULL REFERENCES HIDROMETRO,
DATA_LEITURA DATETIME NOT NULL,
LEITURA_ANTERIOR DECIMAL(5,2) NOT NULL,
LEITURA_ATUAL DECIMAL(5,2) NOT NULL,
CONSUMO DECIMAL(5,2) NOT NULL,
MEDIA_CONSUMO DECIMAL(5,2) NOT NULL);

CREATE TABLE ENDERECO_CLIENTE(
COD_ENDERECO_CLIENTE INT PRIMARY KEY,
COD_CLIENTE INT NOT NULL REFERENCES CLIENTE,
COD_ENDERECO INT NOT NULL REFERENCES ENDERECO,
DATA_INICIO DATETIME NOT NULL,
DATA_TERMINO DATETIME NOT NULL
);

CREATE TABLE GERENCIAR(
COD_GERENCIA INT PRIMARY KEY,
COD_FUNCIONARIO INT NOT NULL REFERENCES FUNCIONARIO,
COD_HIDROMETRO INT NOT NULL REFERENCES HIDROMETRO,
DATA_INICIO DATETIME NOT NULL,
DATA_TERMINO DATETIME NOT NULL
);